lane :test do
  get_rollout_percentage(
    service_account_path: 'path/service_account.json',
    package_name: 'my.project.name',
    track: "production"
  )

  get_version_name(
    service_account_path: 'path/service_account.json',
    package_name: 'my.project.name',
    track: "production"
  )

  update_rollout(
    service_account_path: 'path/service_account.json',
    package_name: 'my.project.name',
    track: "production"
  )
end
